# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Frontend to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4
        with:
          working-directory: frontend

      - name: Clean working directory
        run: git clean -fdx

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use Node.js 20

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Build Next.js application
        working-directory: frontend
        run: npm run build
                
      - name: Prepare standalone build
        run: |
          # Copy public files to standalone directory
          cp -r frontend/public frontend/.next/standalone/
          
          # Copy static files to standalone directory
          mkdir -p frontend/.next/standalone/.next/static
          cp -r frontend/.next/static/* frontend/.next/standalone/.next/static/

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: frontend/.next/standalone/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'tech0-gen-11-step3-2-node-24'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D47ADA76AF4E4023AE6167381174D5E5 }}